name: opifex
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - adwaita-icon-theme=48.1=unix_1
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.9.1=hac33072_0
  - at-spi2-atk=2.38.0=h0630a04_3
  - at-spi2-core=2.40.3=h0630a04_0
  - atk-1.0=2.38.0=h04ea711_2
  - attr=2.5.2=h39aace5_0
  - audioop-lts=0.2.2=py313h54dd161_1
  - audioread=3.0.1=py313h78bf25f_2
  - baumwelch=0.3.10=hb700be7_0
  - biopython=1.85=py313h07c4f96_2
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py313h7033f15_4
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py313hf01b4d8_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py313h7037e92_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dataclassy=1.0.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h3c4dab8_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - epoxy=1.5.10=h166bdaf_1
  - ffmpeg=8.0.0=gpl_hc3e963e_905
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.0=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.1=h2b0a6b4_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - glib-tools=2.86.0=hf516916_0
  - glslang=15.4.0=h7d2aa7d_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - graphviz=13.1.2=h87b6fe6_0
  - greenlet=3.2.4=py313h7033f15_1
  - gtk3=3.24.43=h0c6a113_5
  - gts=0.7.6=h977cf35_4
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=11.5.0=h15599e2_0
  - hdbscan=0.8.39=py313h29aa505_1
  - hicolor-icon-theme=0.17=ha770c72_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-gmmlib=22.8.2=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kaldi=5.5.1172=cpu_ha6a0dec_1
  - kalpy=0.8.2=py313h7037e92_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_1
  - kneed=0.8.5=pyhd8ed1ab_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.24.2=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libass=0.17.4=h96ad9f0_0
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=35_h0358290_openblas
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.24=h86f0d12_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgd=2.3.3=h6f5c62b_11
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.0=h1fed272_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.1.0=h767d61c_5
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblapacke=3.9.0=35_h6ae95b6_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.5.2=hd0c01bc_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=17.6=h3675c94_1
  - libprotobuf=6.31.1=h9ef548d_1
  - librosa=0.11.0=pyhd8ed1ab_0
  - librsvg=2.58.4=he92a37e_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=257.9=h996ca69_0
  - libtiff=4.7.0=h8261f1e_6
  - libudev1=257.9=h085a93f_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.1=he9a06e4_0
  - libva=2.22.0=h4f16b4b_2
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.8=h04c0eec_1
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.44.0=py313hfdae721_2
  - lz4-c=1.10.0=h5888daf_1
  - mad=0.15.1b=h9c3ff4c_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.10.6=py313h683a580_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - montreal-forced-aligner=3.3.4=pyhd8ed1ab_0
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.1=py313h7037e92_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - ngram=1.3.11=hc9558a2_1
  - numba=0.61.2=py313h50b8c88_1
  - numpy=2.2.6=py313h17eae1a_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openfst=1.8.4=h84d6215_1
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.3=h55fea9a_1
  - openldap=2.6.10=he970967_0
  - openssl=3.5.3=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pgvector=0.8.1=h64af21c_0
  - pgvector-python=0.4.1=pyhc48fcf7_0
  - pillow=11.3.0=py313ha492abd_3
  - pip=25.2=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.4.0=pyhcf101f3_0
  - pooch=1.8.2=pyhd8ed1ab_3
  - postgresql=17.6=h021f68a_1
  - praatio=6.2.0=pyhd8ed1ab_1
  - psycopg2=2.9.10=py313h6ad3946_2
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a8bead_2
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynini=2.1.7=py313h7037e92_0
  - pyparsing=3.2.4=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - pysoundfile=0.13.1=pyhd8ed1ab_0
  - python=3.13.7=h2b335a9_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=8_cp313
  - pyyaml=6.0.2=py313h8060acc_2
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.1.0=pyhe01879c_0
  - rich-click=1.9.0=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py313h06d4379_0
  - scipy=1.16.2=py313h11c21cd_0
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.22=h68140b3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.3=h3e344bc_1
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sox=14.4.2=h59a48fd_1020
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=1.0.0=py313h7033f15_0
  - spirv-tools=2025.1=h84d6215_0
  - sqlalchemy=2.0.43=py313h07c4f96_0
  - sqlite=3.50.4=hbc0de68_0
  - standard-aifc=3.13.0=py313h78bf25f_2
  - standard-chunk=3.13.0=pyhd8ed1ab_0
  - standard-sunau=3.13.0=py313h78bf25f_2
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.2.0=hb60516a_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tqdm=4.67.1=pyhd8ed1ab_1
  - tzcode=2025b=hb9d3cd8_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.24.0=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.45=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.25.0=py313h54dd161_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - attrs==25.3.0
      - h11==0.16.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - outcome==1.3.0.post0
      - proglog==0.1.12
      - python-dotenv==1.1.1
      - selenium==4.35.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - trio==0.30.0
      - trio-websocket==0.12.2
      - typing-extensions==4.14.1
      - websocket-client==1.8.0
      - wsproto==1.2.0
prefix: /home/valerio/miniconda3/envs/opifex
